version: '3'
services:
  flask:
      container_name: asr_flask
      image: "21jun/asr_flask"
      ports:
       - "5000:5000"
      networks:
      - backend
  nginx:
      container_name: asr_flask_nginx
      image: "21jun/asr_flask_nginx"
      ports:
       - "80:80"
      networks:
       - backend

networks:
  backend:
    driver: bridge
